CREATE TABLESPACE 테이블스페이스명
DATAFILE 데이타파일전체경로
SIZE 크기(M)
AUTOEXTEND ON NEXT 크기(M);

CREATE USER 유저아이디 IDENTIFIED BY 유저비밀번호
DEFAULT TABLESPACE 테이블스페이스명
QUOTA UNLIMITED ON 테이블스페이스명
TEMPORARY TABLESPACE TEMP;

GRANT 권한 TO EXuser;
